# Generated by Django 2.0.6 on 2018-06-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='jerseyNumber',
            field=models.IntegerField(null=True),
        ),
    ]
