# Generated by Django 2.0.6 on 2018-06-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180610_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cups',
            field=models.IntegerField(default=0),
        ),
    ]
