# Generated by Django 2.0.6 on 2018-06-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_team_cups'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='world_cups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='world_cups_win',
            field=models.IntegerField(default=0),
        ),
    ]
