# Generated by Django 2.0.6 on 2018-06-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180610_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='world_cups_win',
            new_name='world_cups_won',
        ),
    ]
