# Generated by Django 2.0.6 on 2018-06-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_player_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='finals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='semifinals',
            field=models.IntegerField(default=0),
        ),
    ]
