# Generated by Django 2.0.6 on 2018-06-11 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
    ]
