# Generated by Django 2.0.6 on 2018-06-11 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180611_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='team',
            new_name='teams',
        ),
        migrations.RemoveField(
            model_name='group',
            name='goals_received',
        ),
        migrations.RemoveField(
            model_name='group',
            name='goals_scored',
        ),
        migrations.RemoveField(
            model_name='group',
            name='points',
        ),
    ]
