# Generated by Django 2.0.6 on 2018-06-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180611_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teams',
        ),
        migrations.AddField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(to='dashboard.Team'),
        ),
    ]
