# Generated by Django 2.0.6 on 2018-06-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180611_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='goals_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='goals_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
