# Generated by Django 2.0.6 on 2018-06-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20180613_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.CharField(choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D'), ('E', 'Grupo E'), ('F', 'Grupo F'), ('G', 'Grupo G'), ('H', 'Grupo H')], default='A', max_length=1),
        ),
    ]
