# Generated by Django 2.0.6 on 2018-06-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='goals_team1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='goals_team2',
            field=models.IntegerField(default=0),
        ),
    ]
