# Generated by Django 2.0.6 on 2018-06-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20180613_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='played_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='won',
            field=models.IntegerField(default=0),
        ),
    ]
