# Generated by Django 2.0.6 on 2018-06-13 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20180613_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D'), ('E', 'Grupo E'), ('F', 'Grupo F'), ('G', 'Grupo G'), ('H', 'Grupo H')], default='A', max_length=1)),
                ('round', models.CharField(choices=[('1er', 'Primera fase'), ('8vo', 'Octavos'), ('4to', 'Cuarto'), ('Semi', 'Semifinales'), ('3er', 'Tercer lugar'), ('Final', 'Finales')], default='1er', max_length=1)),
                ('played_matches', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='team',
            name='group',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lose',
        ),
        migrations.RemoveField(
            model_name='team',
            name='played_matches',
        ),
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='won',
        ),
        migrations.AddField(
            model_name='match',
            name='source',
            field=models.CharField(default='', max_length=48),
        ),
        migrations.AddField(
            model_name='round',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Team'),
        ),
    ]
