# Generated by Django 2.0.6 on 2018-06-14 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20180614_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='Oficial', max_length=48)),
                ('goals_team1', models.IntegerField(default=0)),
                ('goals_team2', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='firstmatch',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='firstmatch',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='goals_team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='goals_team2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='source',
        ),
        migrations.DeleteModel(
            name='FirstMatch',
        ),
        migrations.AddField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Match'),
        ),
    ]
