# Generated by Django 2.0.6 on 2018-06-14 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20180614_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='team1',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bteam1', to='dashboard.Team'),
        ),
        migrations.AddField(
            model_name='bet',
            name='team2',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bteam2', to='dashboard.Team'),
        ),
    ]
