# Generated by Django 2.0.6 on 2018-06-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_gambler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gambler',
            name='points_3er',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gambler',
            name='points_4vo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gambler',
            name='points_8vo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gambler',
            name='points_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gambler',
            name='points_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gambler',
            name='points_semi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gambler',
            name='points_winner',
            field=models.IntegerField(default=0),
        ),
    ]
