# Generated by Django 2.0.6 on 2018-06-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20180614_0512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gambler',
            old_name='source',
            new_name='name',
        ),
    ]
