# Generated by Django 2.0.6 on 2018-06-14 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20180614_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Gambler'),
        ),
    ]
