# Generated by Django 2.0.6 on 2018-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20180614_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='group',
            field=models.CharField(choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D'), ('E', 'Grupo E'), ('F', 'Grupo F'), ('G', 'Grupo G'), ('H', 'Grupo H')], max_length=1, null=True),
        ),
    ]
