# Generated by Django 2.0.6 on 2018-06-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20180614_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='round',
            field=models.CharField(choices=[('1', 'Primera fase'), ('2', 'Octavos'), ('3', 'Cuarto'), ('4', 'Semifinales'), ('5', 'Tercer lugar'), ('6', 'Finales')], default='1', max_length=1),
        ),
    ]
