# Generated by Django 2.0.6 on 2018-06-15 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20180614_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='round',
            new_name='stage',
        ),
        migrations.AlterField(
            model_name='bet',
            name='goals_team1',
            field=models.IntegerField(default=0, verbose_name='Goles equipo 1'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='goals_team2',
            field=models.IntegerField(default=0, verbose_name='Goles equipo 2'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Match', verbose_name='Partido de referencia'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Gambler', verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='team1',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bteam1', to='dashboard.Team', verbose_name='Equipo 1'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='team2',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bteam2', to='dashboard.Team', verbose_name='Equipo 2'),
        ),
    ]
