# Generated by Django 2.0.6 on 2018-06-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20180615_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
