# Generated by Django 2.0.6 on 2018-06-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20180616_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='match',
            name='game_date',
            field=models.DateTimeField(null=True),
        ),
    ]
