# Generated by Django 2.0.6 on 2018-06-23 05:44

from django.db import migrations


def set_group(apps, schema_editor):
    Team = apps.get_model('dashboard', 'Team')
    Round = apps.get_model('dashboard', 'Round')
    for team in Team.objects.all():
        round = Round.objects.filter(team=team).first()
        team.group = round.group
        team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_team_group'),
    ]

    operations = [
        migrations.RunPython(set_group),
    ]
