# Generated by Django 2.0.6 on 2018-06-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20180623_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='group',
        ),
    ]
