# Generated by Django 2.0.6 on 2018-06-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_remove_round_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['stage', 'team__group']},
        ),
        migrations.AddField(
            model_name='round',
            name='goals_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='goals_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='goals_for',
            field=models.IntegerField(default=0),
        ),
    ]
