# Generated by Django 2.0.6 on 2018-06-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20180626_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='position',
            field=models.CharField(default='', max_length=24),
        ),
    ]
