# Generated by Django 2.0.6 on 2018-06-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_round_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
