# Generated by Django 2.0.6 on 2018-06-26 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_round_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Gambler'),
        ),
    ]
