# Generated by Django 2.0.6 on 2018-06-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_round_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('1', 'Primera fase'), ('2', 'Octavos'), ('3', 'Cuarto'), ('4', 'Semifinales'), ('5', 'Tercer lugar'), ('6', 'Finales')], default='1', max_length=1),
        ),
    ]
