# Generated by Django 2.0.6 on 2018-06-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_match_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='qualified_revision',
            field=models.BooleanField(default=False),
        ),
    ]
