# Generated by Django 2.0.6 on 2018-06-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_auto_20180630_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='type',
            field=models.CharField(default='Original', max_length=32, null=True),
        ),
    ]
