# Generated by Django 2.0.6 on 2018-06-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_bet_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together={('source', 'match', 'type')},
        ),
    ]
