# Generated by Django 2.0.6 on 2018-06-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20180630_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='gambler',
            name='points_result2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gambler',
            name='points_score2',
            field=models.IntegerField(default=0),
        ),
    ]
