# Generated by Django 2.0.6 on 2018-06-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_auto_20180630_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='gambler',
            name='points_3er2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gambler',
            name='points_4vo2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gambler',
            name='points_final2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gambler',
            name='points_semi2',
            field=models.IntegerField(default=0),
        ),
    ]
