# Generated by Django 2.0.6 on 2018-07-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20180630_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('1', 'Primera fase'), ('2', 'Octavos'), ('3', 'Cuartos'), ('4', 'Semifinales'), ('5', 'Tercer lugar'), ('6', 'Finales')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='round',
            name='stage',
            field=models.CharField(choices=[('1', 'Primera fase'), ('2', 'Octavos'), ('3', 'Cuartos'), ('4', 'Semifinales'), ('5', 'Tercer lugar'), ('6', 'Finales')], default='1', max_length=1),
        ),
    ]
